### ISSUE TITLE
[Bug] RC4 out of bounds exception

### ISSUE THREAD

**Issue by Aodai** [iSmokeDrow/Navislamia#2]
This is just a reminder to fix this issue that was introduced by #1 
![unknown-6](https://user-images.githubusercontent.com/5209943/160235003-cf9da42c-6814-4842-8467-af4c2a3382c6.png)

**Comment by iSmokeDrow** [comment]
Just a side note:

- It happens during the construction of the RC4Cipher class called by the GameNetwork 
- Relatively sure this did not happen with the previous version (ported from Vanilla)
